### ISSUE TITLE
Add ability to build triton_fil Docker image with cuML nightly

### ISSUE THREAD

**Issue by hcho3** [triton-inference-server/fil_backend#86]
Customers may want to try out new improvements that are available in nightly builds of cuML, e.g. improvements in FIL or Treelite. It would be great to provide an option to build `triton_fil` Docker image with a nightly version of cuML.

Currently, `trition_fil` is built with the latest stable version of cuML.

**Comment by wphicks** [comment]
I'm not _entirely_ opposed to having a flag like this for convenience, but I'm not sure we necessarily want to encourage this. Even internally, we will probably have the policy that we only develop and support changes to this backend based on a fully-released version of cuML in order to avoid issues with coordinating release calendars between RAPIDS and Triton. For those who are aware of the dangers and willing to bleed a little on that bleeding edge, it's easy enough to flip the conda channel over to `rapidsai-nightly`, but I worry that having infrastructure in place that explicitly supports this will make it seem like this is a supported usecase. Most of all, we don't want to have to start tracking down bugs or untangling dependency issues based on an unreleased version of RAPIDS.

Does that make sense to you @hcho3? If so, I'll close this, but if not we can leave it open for further discussion.

**Comment by hcho3** [comment]
> it's easy enough to flip the conda channel over to rapidsai-nightly

If it's just matter of changing the conda channel, I suppose it's fine.
